export default function getPokedex() {
  return [
    {
      id: 1,
      name: "Houndour",
      evolution: "Houndoom",
      basic: true,
    },
    {
      id: 2,
      name: "Houndoom",
      evolution: null,
      basic: false,
    },
    {
      id: 3,
      name: "Abra",
      evolution: "Kadabra",
      basic: true,
    },
    {
      id: 4,
      name: "Kadabra",
      evolution: "Alakazam",
      basic: false,
    },
    {
      id: 5,
      name: "Alakazam",
      evolution: null,
      basic: false,
    },
    {
      id: 6,
      name: "Gastly",
      evolution: "Haunter",
      basic: true,
    },
    {
      id: 7,
      name: "Haunter",
      evolution: "Gengar",
      basic: false,
    },
    {
      id: 8,
      name: "Gengar",
      evolution: null,
      basic: false,
    },
    {
      id: 9,
      name: "Misdreavus",
      evolution: "Mismagius",
      basic: true,
    },
    {
      id: 10,
      name: "Mismagius",
      evolution: null,
      basic: false,
    },
    {
      id: 11,
      name: "Larvitar",
      evolution: "Pupitar",
      basic: true,
    },
    {
      id: 12,
      name: "Pupitar",
      evolution: "Tyranitar",
      basic: false,
    },
    {
      id: 13,
      name: "Tyranitar",
      evolution: null,
      basic: false,
    },
    {
      id: 14,
      name: "Cleffa",
      evolution: "Clefairy",
      basic: true,
    },
    {
      id: 15,
      name: "Clefairy",
      evolution: "Clefable",
      basic: false,
    },
    {
      id: 16,
      name: "Clefable",
      evolution: null,
      basic: false,
    },
    {
      id: 17,
      name: "Togepi",
      evolution: "Togetic",
      basic: true,
    },
    {
      id: 18,
      name: "Togetic",
      evolution: "Togekiss",
      basic: false,
    },
    {
      id: 19,
      name: "Togekiss",
      evolution: null,
      basic: false,
    },
    {
      id: 20,
      name: "Happiny",
      evolution: "Chansey",
      basic: true,
    },
    {
      id: 21,
      name: "Chansey",
      evolution: "Blissey",
      basic: false,
    },
    {
      id: 22,
      name: "Blissey",
      evolution: null,
      basic: false,
    },
    {
      id: 23,
      name: "Igglybuff",
      evolution: "Jigglypuff",
      basic: true,
    },
    {
      id: 24,
      name: "Jigglypuff",
      evolution: "Wigglytuff",
      basic: false,
    },
    {
      id: 25,
      name: "Wigglytuff",
      evolution: null,
      basic: false,
    },
    {
      id: 26,
      name: "Azurill",
      evolution: "Marill",
      basic: true,
    },
    {
      id: 27,
      name: "Marill",
      evolution: "Azumarill",
      basic: false,
    },
    {
      id: 28,
      name: "Azumarill",
      evolution: null,
      basic: false,
    },
    {
      id: 29,
      name: "Cyndaquil",
      evolution: "Quilava",
      basic: true,
    },
    {
      id: 30,
      name: "Quilava",
      evolution: "Typhlosion",
      basic: false,
    },
    {
      id: 31,
      name: "Typhlosion",
      evolution: null,
      basic: false,
    },
    {
      id: 32,
      name: "Fennekin",
      evolution: "Braixen",
      basic: true,
    },
    {
      id: 33,
      name: "Braixen",
      evolution: "Delphox",
      basic: false,
    },
    {
      id: 34,
      name: "Delphox",
      evolution: null,
      basic: false,
    },
    {
      id: 35,
      name: "Charmander",
      evolution: "Charmeleon",
      basic: true,
    },
    {
      id: 36,
      name: "Charmeleon",
      evolution: "Charizard",
      basic: false,
    },
    {
      id: 37,
      name: "Charizard",
      evolution: null,
      basic: false,
    },
    {
      id: 38,
      name: "Vulpix",
      evolution: "Ninetales",
      basic: true,
    },
    {
      id: 39,
      name: "Ninetales",
      evolution: null,
      basic: false,
    },
    {
      id: 40,
      name: "Growlithe",
      evolution: "Arcanine",
      basic: true,
    },
    {
      id: 41,
      name: "Arcanine",
      evolution: null,
      basic: false,
    },
    {
      id: 42,
      name: "Dratini",
      evolution: "Dragonair",
      basic: true,
    },
    {
      id: 43,
      name: "Dragonair",
      evolution: "Dragonite",
      basic: false,
    },
    {
      id: 44,
      name: "Dragonite",
      evolution: null,
      basic: false,
    },
    {
      id: 45,
      name: "Swablu",
      evolution: "Altaria",
      basic: true,
    },
    {
      id: 46,
      name: "Altaria",
      evolution: null,
      basic: false,
    },
    {
      id: 47,
      name: "Gible",
      evolution: "Gabite",
      basic: true,
    },
    {
      id: 48,
      name: "Gabite",
      evolution: "Garchomp",
      basic: false,
    },
    {
      id: 49,
      name: "Garchomp",
      evolution: null,
      basic: false,
    },
    {
      id: 50,
      name: "Scyther",
      evolution: "Scizor",
      basic: true,
    },
    {
      id: 51,
      name: "Scizor",
      evolution: null,
      basic: false,
    },
    {
      id: 52,
      name: "Zubat",
      evolution: "Golbat",
      basic: true,
    },
    {
      id: 53,
      name: "Golbat",
      evolution: "Crobat",
      basic: false,
    },
    {
      id: 54,
      name: "Crobat",
      evolution: null,
      basic: false,
    },
    {
      id: 55,
      name: "Pichu",
      evolution: "Pikachu",
      basic: true,
    },
    {
      id: 56,
      name: "Pikachu",
      evolution: "Raichu",
      basic: false,
    },
    {
      id: 57,
      name: "Raichu",
      evolution: null,
      basic: false,
    },
    {
      id: 58,
      name: "Elekid",
      evolution: "Electabuzz",
      basic: true,
    },
    {
      id: 59,
      name: "Electabuzz",
      evolution: "Electivire",
      basic: false,
    },
    {
      id: 60,
      name: "Mareep",
      evolution: "Flaaffy",
      basic: true,
    },
    {
      id: 61,
      name: "Flaaffy",
      evolution: "Ampharos",
      basic: false,
    },
    {
      id: 62,
      name: "Ampharos",
      evolution: null,
      basic: false,
    },
    {
      id: 63,
      name: "Shinx",
      evolution: "Luxio",
      basic: true,
    },
    {
      id: 64,
      name: "Luxio",
      evolution: "Luxray",
      basic: false,
    },
    {
      id: 65,
      name: "Luxray",
      evolution: null,
      basic: false,
    },
    {
      id: 66,
      name: "Magnemite",
      evolution: "Magneton",
      basic: true,
    },
    {
      id: 67,
      name: "Magneton",
      evolution: "Magnezone",
      basic: false,
    },
    {
      id: 68,
      name: "Magnezone",
      evolution: null,
      basic: false,
    },
    {
      id: 69,
      name: "Magikarp",
      evolution: "Gyarados",
      basic: true,
    },
    {
      id: 70,
      name: "Gyarados",
      evolution: null,
      basic: false,
    },
    {
      id: 71,
      name: "Poliwag",
      evolution: "Poliwhirl",
      basic: true,
    },
    {
      id: 72,
      name: "Poliwhirl",
      evolution: "Poliwrath",
      basic: false,
    },
    {
      id: 73,
      name: "Poliwrath",
      evolution: null,
      basic: false,
    },
    {
      id: 74,
      name: "Horsea",
      evolution: "Seadra",
      basic: true,
    },
    {
      id: 75,
      name: "Seadra",
      evolution: "Kingdra",
      basic: false,
    },
    {
      id: 76,
      name: "Kingdra",
      evolution: null,
      basic: false,
    },
    {
      id: 77,
      name: "Totodile",
      evolution: "Croconaw",
      basic: true,
    },
    {
      id: 78,
      name: "Croconaw",
      evolution: "Feraligatr",
      basic: false,
    },
    {
      id: 79,
      name: "Feraligatr",
      evolution: null,
      basic: false,
    },
    {
      id: 80,
      name: "Psyduck",
      evolution: "Golduck",
      basic: true,
    },
    {
      id: 81,
      name: "Golduck",
      evolution: null,
      basic: false,
    },
  ];
}
